### ISSUE TITLE
`bin/hubot` error

### ISSUE THREAD

**Issue by vzvenyach** [18F/18f-bot#60]
Trying to test out hubot locally and got this error...

```
config/slack-github-issues.json: OK
Hubot> XPOST script loaded.
WARNING: No configurations found in configuration directory:/Users/vladlenzvenyach/Coding/18f-bot/config
WARNING: To disable this warning set SUPRESS_NO_CONFIG_WARNING in the environment.
[Fri Feb 19 2016 05:37:55 GMT-0800 (PST)] INFO hubot-slack-github-issues: loading
[Fri Feb 19 2016 05:37:55 GMT-0800 (PST)] INFO hubot-slack-github-issues: reading configuration from config/slack-github-issues.json
[Fri Feb 19 2016 05:37:55 GMT-0800 (PST)] INFO hubot-slack-github-issues: registered receiveMiddleware
[Fri Feb 19 2016 05:37:55 GMT-0800 (PST)] WARNING The HUBOT_AUTH_ADMIN environment variable not set
[Fri Feb 19 2016 05:37:55 GMT-0800 (PST)] INFO Using default redis on localhost:6379
[Fri Feb 19 2016 05:37:55 GMT-0800 (PST)] INFO Data for hubot brain retrieved from Redis
[Fri Feb 19 2016 05:38:00 GMT-0800 (PST)] ERROR Error: Please set HUBOT_CF_UAA_ORIGIN.
  at /Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/credentials.coffee:13:50, <js>:19:15
  at Object.module.exports.uaaOrigin (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/credentials.coffee:12:14, <js>:20:9)
  at Object.module.exports.requestOpts (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/credentials.coffee:17:5, <js>:24:19)
  at Object.module.exports.fetchTokenObj (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/credentials.coffee:31:12, <js>:39:19)
  at Object.module.exports.call (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/client.coffee:22:5, <js>:30:26)
  at Object.module.exports.getUpdateEvents (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/event_checker.coffee:18:5, <js>:20:21)
  at Object.module.exports.getDeployEntities (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/event_checker.coffee:33:5, <js>:36:19)
  at Object.module.exports.notify (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/notifier.coffee:18:5, <js>:29:22)
  at [object Object]._repeat (/Users/vladlenzvenyach/Coding/18f-bot/node_modules/hubot-cf-notifications/src/notifier.coffee:26:7, <js>:38:15)
  at [object Object].wrapper [as _onTimeout] (timers.js:270:19)
  at Timer.listOnTimeout (timers.js:89:15)
```

**Comment by vzvenyach** [comment]
FWIW, i'm pretty sure the source of the error is `hubot-cf-notifications` (https://github.com/18F/hubot-cf-notifications), so will x-post there.
