### ISSUE TITLE
exception from hubot-slack

### ISSUE THREAD

**Issue by afeld** [18F/18f-bot#65]
This bug report probably belongs in a different repository, but wanted to place it here since I'm seeing it several times in the logs and don't want to lose it.

```
[Fri Mar 18 2016 19:05:37 GMT+0000 (UTC)] ERROR TypeError: Cannot read property '0' of undefined
  at Client.getChannelGroupOrDMByID (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/src/client.js:369:11)
  at SlackBot.reactionAdded (/home/vcap/app/node_modules/hubot-slack/src/slack.coffee:180:23)
  at Client.<anonymous> (/home/vcap/app/node_modules/hubot-slack/src/slack.coffee:1:1)
  at emitOne (events.js:77:13)
  at Client.emit (events.js:169:7)
  at Client.onMessage (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/src/client.js:620:21)
  at WebSocket.<anonymous> (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/src/client.js:149:24)
  at emitTwo (events.js:87:13)
  at WebSocket.emit (events.js:172:7)
  at Receiver.ontext (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:816:10)
  at /home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:477:18
  at Receiver.applyExtensions (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:364:5)
  at /home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:466:14
  at Receiver.flush (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:340:3)
  at Receiver.opcodes.1.finish (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:482:12)
  at Receiver.expectHandler (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:457:31)
  at Receiver.add (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:95:24)
  at TLSSocket.realHandler (/home/vcap/app/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:800:20)
  at emitOne (events.js:77:13)
  at TLSSocket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at TLSSocket.Readable.push (_stream_readable.js:110:10)
  at TLSWrap.onread (net.js:523:20)
```

Dependencies:

```
$ npm list | grep slack
├─┬ hubot-slack@3.4.2 (git://github.com/18f/hubot-slack.git#1f38b6ef87d365486e8951a5c207a734a5b32faa)
│ └─┬ slack-client@1.5.0 (git://github.com/18f/node-slack-client.git#16a5995e9eaeec054c5320737ca3573895444523)
├── hubot-slack-github-issues@1.0.2
```

**Comment by mgwalker** [comment]
Haven't seen this in the logs recently, and the `slack-client` module was replaced with a heavily refactored `@slack/client` module that no longer has a `getChannelGroupOrDMByID` method.  My guess is it was an issue either in Hubot or the slack client that has been fixed.
